name: "ğŸ” Code analysis"

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  eslint:
    name: "ğŸ” Scan with eslint"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: "âŒ› Checking out the code"
        uses: actions/checkout@v3

      - name: "ğŸ“¦ Installing eslint"
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: "â–¶ï¸ Running eslint"
        run: npx eslint .
          --config .eslintrc.cjs
          --ext .js,.ts
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: false

      - name: "ğŸ“© Upload analysis results to GitHub"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
