env:
  SFTP_HOST: ${{ secrets.FTP_SERVER }}
  SFTP_PORT: ${{ secrets.FTP_PORT }}
  SFTP_USER: ${{ secrets.FTP_USERNAME }}
  SFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
  
on: push
name: ğŸš€ Deploy to production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "âš™ï¸ Preparing for sftp deployment"
      uses: actions/checkout@v3
    - name: "âš™ï¸ Getting node"
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: "ğŸ“¦ Getting dependencies (1/2)"
      run: npm install dotenv
    - name: "ğŸ“¦ Getting dependencies (2/2)"
      run: npm install sftp-upload
    - name: "ğŸ“ Sending project files to production"
      run: npm run deploy
      