env:
  SFTP_HOST: ${{ secrets.FTP_SERVER }}
  SFTP_PORT: ${{ secrets.FTP_PORT }}
  SFTP_USER: ${{ secrets.FTP_USERNAME }}
  SFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  
on: 
  push:
    branches:
      - master

name: "ğŸš€ Deploy to production"
jobs:

  build:
    name: "âš’ï¸ Register commands at discord"
    runs-on: ubuntu-latest
    steps:
    - name: "âŒ› Checking out the code"
      uses: actions/checkout@v3
    - name: "âš™ï¸ Polishing the gears"
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: "ğŸ“¦ Getting dependencies (1/3)"
      run: npm install dotenv
    - name: "ğŸ“¦ Getting dependencies (1/3)"
      run: npm install @discordjs/rest 
    - name: "ğŸ“¦ Getting dependencies (1/3)"
      run: npm install @discord-api-types/v10
    - name: "âœï¸ Registering commands at discord"
      run: npm run register

  deploy:
    name: "ğŸšš Deploy sourcecode to production"
    runs-on: ubuntu-latest
    steps:
    - name: "âŒ› Checking out the code"
      uses: actions/checkout@v3
    - name: "âš™ï¸ Polishing the gears"
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: "ğŸ“¦ Getting dependencies (1/2)"
      run: npm install dotenv
    - name: "ğŸ“¦ Getting dependencies (2/2)"
      run: npm install ssh2-sftp-client
    - name: "ğŸ“ Sending project files to production"
      run: npm run deploy
      